#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlets core::stream::infer

#
# Parses a (simplified) YAML file.
# Based on http://stackoverflow.com/questions/5014632/.
#

#@public
function bashlets::text::parser::yaml::to_keyvalues()
{
    local file="$1"
    local prefix="$2"
    local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo -ne '\034')
    local indent_step

    test -e "$file" || return

    indent_step="$($BASHLETS_NAMESPACE infer indent_step < "$file")"
	
	sed                                                                     \
		-ne "s|^\($s\):|\1|"                                                \
		-e  "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p"       \
		-e  "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"   "$file"       \
																			\
	| awk -v indent_step="$indent_step" -v fs="$fs" -F"$fs" '{
		indent = length($1)/indent_step;
		vname[indent] = $2;
		for (i in vname) {if (i > indent) {delete vname[i]}}
		if (length($3) > 0) {
			vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
			printf("%s%s%s"(fs)"%s\n", "'$prefix'", vn, $2, $3);
		}
	}'
}


#@public
function bashlets::text::parser::yaml::keys()
{
    local file="$1"
    local prefix="$2"

    bashlets::text::parser::yaml::to_keyvalues "$file" "$prefix"             \
        | cut -d$(echo -ne '\034') -f1
}

#@public
function bashlets::text::parser::yaml::values()
{
    local file="$1"
    local prefix="$2"

    bashlets::text::parser::yaml::to_keyvalues "$file" "$prefix"             \
        | cut -d$(echo -ne '\034') -f2
}

#@public
function bashlets::text::parser::yaml::get()
{
    local file="$1"
    local key="$2"
    local prefix="$3"

    bashlets::text::parser::yaml::to_keyvalues "$file" "$prefix"             \
        | awk -F$(echo -ne '\034') "\$1 ~ /^$key$/ { print \$2 }"
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
